apiVersion: v1
kind: Secret
metadata:
  name: cybersapient-backend-secret
  namespace: prod
  labels:
    app: cybersapient-backend
    tier: backend
type: Opaque
data:
  # Base64 encoded DATABASE_URL
  # Format: postgresql://cybersapient-demo:075mpJ4Gn6@cybersapient-postgres-postgresql.prod.svc.cluster.local:5432/cybersapient
  # Update this with your actual credentials (base64 encoded)
  database-url: cG9zdGdyZXNxbDovL2N5YmVyc2FwaWVudC1kZW1vOjA3NW1wSjRHbjZAY3liZXJzYXBpZW50LXBvc3RncmVzLXBvc3RncmVzcWwucHJvZC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2N5YmVyc2FwaWVudA==

# To update the secret with your actual credentials, run:
# echo -n "postgresql://your_user:your_password@cybersapient-postgres-postgresql.prod.svc.cluster.local:5432/cybersapient" | base64