apiVersion: v1
kind: Service
metadata:
  name: cybersapient-backend-service
  namespace: prod
  labels:
    app: cybersapient-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: cybersapient-backend