
ingress-nginx:
  controller:
    config:
      annotations-risk-level: "Critical"
    allowSnippetAnnotations: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
    replicaCount: 1
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    affinity: 
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - ingress-nginx
            topologyKey: "kubernetes.io/hostname"
    metrics:
      enabled: true

