apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cybersapient-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amarthyanathb/argo-apps.git
    targetRevision: HEAD
    path: argo-manifest/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true